Create hook update to update resources without group but dataset pare…
GetDKAN/dkan_dataset pull request #287
Opened 2016-11-04 00:05 UTC by jacintocapote

…nt has groups

2016-12-13 21:18 UTC, dafeder requested changes
A couple questions about the update hook @jacintocapote

2016-12-13 21:18 UTC, dafeder commented on modules/dkan_dataset_groups/dkan_dataset_groups.install
> +  $result = db_query("SELECT fdr.field_dataset_ref_target_id FROM {node} n LEFT JOIN {field_data_field_dataset_ref fdr} ON fdr.entity_id=n.nid LEFT JOIN {og_membership} og ON n.nid=og.etid WHERE n.ty
We are wondering if this query will catch and correctly update resources that belong to two different datasets.

2016-12-13 21:18 UTC, dafeder commented on modules/dkan_dataset_groups/dkan_dataset_groups.install
> +    //Simulate a empty original
Same question as above - does this work correctly with resources that belong to more than one dataset? If not, we may want to refactor to use different logic than dkan_dataset_sync_groups().

2016-12-13 21:18 UTC, dafeder commented on modules/dkan_dataset_groups/dkan_dataset_groups.install
> + * Update resources without groups with the same group from parent dataset.
I think we need a bit more documentation to explain what this is for.

2016-12-13 21:18 UTC, dafeder commented on modules/dkan_dataset_groups/dkan_dataset_groups.install
> +/**
We should actually be doing all updates in dkan.install, not individual module install files. Move this and the datastore ones to dkan.install (eliminating need for dependencies and extra PRs).

2016-12-14 21:30 UTC, msolv commented
This code has been moved to 'dkan.install' here https://github.com/NuCivic/dkan/pull/1491. Closing this.

2016-12-14 21:30 UTC, closed without merging